import { createConnection, Connection, getRepository } from 'typeorm';
import { Book } from '../src/book/entities/book.entity';

async function seed() {
  try {
    const connection: Connection = await createConnection();

    const bookRepository = getRepository(Book);

    const books = [
      {
        title: 'The Great Gatsby',
        author: 'F. Scott Fitzgerald',
        genre: 'Fiction',
        year: 1925,
        stock: 10,
      },
      {
        title: 'To Kill a Mockingbird',
        author: 'Harper Lee',
        genre: 'Fiction',
        year: 1960,
        stock: 5,
      },
      {
        title: '1984',
        author: 'George Orwell',
        genre: 'Dystopian',
        year: 1949,
        stock: 7,
      },
      {
        title: 'Moby Dick',
        author: 'Herman Melville',
        genre: 'Adventure',
        year: 1851,
        stock: 3,
      },
      {
        title: 'Pride and Prejudice',
        author: 'Jane Austen',
        genre: 'Romance',
        year: 1813,
        stock: 8,
      },
      {
        title: 'The Catcher in the Rye',
        author: 'J.D. Salinger',
        genre: 'Fiction',
        year: 1951,
        stock: 6,
      },
      {
        title: 'The Hobbit',
        author: 'J.R.R. Tolkien',
        genre: 'Fantasy',
        year: 1937,
        stock: 12,
      },
      {
        title: 'Brave New World',
        author: 'Aldous Huxley',
        genre: 'Dystopian',
        year: 1932,
        stock: 9,
      },
      {
        title: 'The Da Vinci Code',
        author: 'Dan Brown',
        genre: 'Thriller',
        year: 2003,
        stock: 15,
      },
      {
        title: 'Wuthering Heights',
        author: 'Emily Brontë',
        genre: 'Gothic',
        year: 1847,
        stock: 4,
      },
      {
        title: 'Jane Eyre',
        author: 'Charlotte Brontë',
        genre: 'Romance',
        year: 1847,
        stock: 7,
      },
      {
        title: 'The Chronicles of Narnia',
        author: 'C.S. Lewis',
        genre: 'Fantasy',
        year: 1950,
        stock: 10,
      },
      {
        title: 'The Shining',
        author: 'Stephen King',
        genre: 'Horror',
        year: 1977,
        stock: 13,
      },
      {
        title: 'Gone with the Wind',
        author: 'Margaret Mitchell',
        genre: 'Historical Fiction',
        year: 1936,
        stock: 8,
      },
      {
        title: 'The Lord of the Rings',
        author: 'J.R.R. Tolkien',
        genre: 'Fantasy',
        year: 1954,
        stock: 20,
      },
      {
        title: 'Fahrenheit 451',
        author: 'Ray Bradbury',
        genre: 'Dystopian',
        year: 1953,
        stock: 14,
      },
      {
        title: 'The Hunger Games',
        author: 'Suzanne Collins',
        genre: 'Dystopian',
        year: 2008,
        stock: 17,
      },
      {
        title: 'The Picture of Dorian Gray',
        author: 'Oscar Wilde',
        genre: 'Philosophical Fiction',
        year: 1890,
        stock: 6,
      },
      {
        title: 'Les Misérables',
        author: 'Victor Hugo',
        genre: 'Historical Fiction',
        year: 1862,
        stock: 5,
      },
      {
        title: 'Dracula',
        author: 'Bram Stoker',
        genre: 'Horror',
        year: 1897,
        stock: 7,
      },
      {
        title: 'Catch-22',
        author: 'Joseph Heller',
        genre: 'Satire',
        year: 1961,
        stock: 9,
      },
      {
        title: 'The Grapes of Wrath',
        author: 'John Steinbeck',
        genre: 'Historical Fiction',
        year: 1939,
        stock: 12,
      },
      {
        title: 'Little Women',
        author: 'Louisa May Alcott',
        genre: 'Coming-of-Age',
        year: 1868,
        stock: 11,
      },
      {
        title: 'Murder on the Orient Express',
        author: 'Agatha Christie',
        genre: 'Mystery',
        year: 1934,
        stock: 8,
      },
      {
        title: 'The Fault in Our Stars',
        author: 'John Green',
        genre: 'Young Adult',
        year: 2012,
        stock: 10,
      },
      {
        title: 'The Road',
        author: 'Cormac McCarthy',
        genre: 'Post-Apocalyptic',
        year: 2006,
        stock: 7,
      },
      {
        title: 'Life of Pi',
        author: 'Yann Martel',
        genre: 'Adventure',
        year: 2001,
        stock: 9,
      },
      {
        title: 'A Tale of Two Cities',
        author: 'Charles Dickens',
        genre: 'Historical Fiction',
        year: 1859,
        stock: 7,
      },
      {
        title: 'The Bell Jar',
        author: 'Sylvia Plath',
        genre: 'Psychological Fiction',
        year: 1963,
        stock: 6,
      },
      {
        title: 'The Old Man and the Sea',
        author: 'Ernest Hemingway',
        genre: 'Literary Fiction',
        year: 1952,
        stock: 8,
      },
      {
        title: 'Slaughterhouse-Five',
        author: 'Kurt Vonnegut',
        genre: 'Science Fiction',
        year: 1969,
        stock: 9,
      },
      {
        title: 'One Hundred Years of Solitude',
        author: 'Gabriel García Márquez',
        genre: 'Magical Realism',
        year: 1967,
        stock: 10,
      },
      {
        title: 'The Handmaid’s Tale',
        author: 'Margaret Atwood',
        genre: 'Dystopian',
        year: 1985,
        stock: 12,
      },
      {
        title: 'A Brave New World',
        author: 'Aldous Huxley',
        genre: 'Science Fiction',
        year: 1932,
        stock: 11,
      },
      {
        title: 'The Secret Garden',
        author: 'Frances Hodgson Burnett',
        genre: 'Children’s Fiction',
        year: 1911,
        stock: 7,
      },
      {
        title: 'The Wonderful Wizard of Oz',
        author: 'L. Frank Baum',
        genre: 'Fantasy',
        year: 1900,
        stock: 6,
      },
      {
        title: 'The Joy Luck Club',
        author: 'Amy Tan',
        genre: 'Contemporary Fiction',
        year: 1989,
        stock: 8,
      },
      {
        title: 'The Godfather',
        author: 'Mario Puzo',
        genre: 'Crime Fiction',
        year: 1969,
        stock: 10,
      },
      {
        title: 'The Outsiders',
        author: 'S.E. Hinton',
        genre: 'Young Adult',
        year: 1967,
        stock: 11,
      },
      {
        title: 'The Sun Also Rises',
        author: 'Ernest Hemingway',
        genre: 'Literary Fiction',
        year: 1926,
        stock: 7,
      },
      {
        title: 'The Call of the Wild',
        author: 'Jack London',
        genre: 'Adventure',
        year: 1903,
        stock: 8,
      },
      {
        title: 'The Sound and the Fury',
        author: 'William Faulkner',
        genre: 'Southern Gothic',
        year: 1929,
        stock: 9,
      },
      {
        title: 'As I Lay Dying',
        author: 'William Faulkner',
        genre: 'Southern Gothic',
        year: 1930,
        stock: 6,
      },
      {
        title: 'The Last of the Mohicans',
        author: 'James Fenimore Cooper',
        genre: 'Historical Fiction',
        year: 1826,
        stock: 5,
      },
      {
        title: 'The Moonstone',
        author: 'Wilkie Collins',
        genre: 'Mystery',
        year: 1868,
        stock: 8,
      },
      {
        title: 'A Clockwork Orange',
        author: 'Anthony Burgess',
        genre: 'Dystopian',
        year: 1962,
        stock: 10,
      },
      {
        title: 'The Heart of Darkness',
        author: 'Joseph Conrad',
        genre: 'Literary Fiction',
        year: 1899,
        stock: 7,
      },
      {
        title: 'The Three Musketeers',
        author: 'Alexandre Dumas',
        genre: 'Historical Fiction',
        year: 1844,
        stock: 9,
      },
      {
        title: 'Don Quixote',
        author: 'Miguel de Cervantes',
        genre: 'Literary Fiction',
        year: 1605,
        stock: 6,
      },
      {
        title: 'The Divine Comedy',
        author: 'Dante Alighieri',
        genre: 'Epic Poetry',
        year: 1320,
        stock: 5,
      },
      {
        title: 'Walt Whitman',
        author: 'Leaves of Grass',
        genre: 'Poetry',
        year: 1855,
        stock: 11,
      },
      {
        title: 'The Little Prince',
        author: 'Antoine de Saint-Exupéry',
        genre: 'Children’s Fiction',
        year: 1943,
        stock: 8,
      },
      {
        title: 'A Midsummer Night’s Dream',
        author: 'William Shakespeare',
        genre: 'Play',
        year: 1595,
        stock: 7,
      },
      {
        title: 'The Road Less Traveled',
        author: 'M. Scott Peck',
        genre: 'Self-Help',
        year: 1978,
        stock: 10,
      },
      {
        title: 'The 7 Habits of Highly Effective People',
        author: 'Stephen R. Covey',
        genre: 'Self-Help',
        year: 1989,
        stock: 12,
      },
      {
        title: 'The Art of War',
        author: 'Sun Tzu',
        genre: 'Philosophy',
        year: -500,
        stock: 9,
      },
      {
        title: 'The Prince',
        author: 'Niccolò Machiavelli',
        genre: 'Political Science',
        year: 1532,
        stock: 6,
      },
      {
        title: 'Sapiens: A Brief History of Humankind',
        author: 'Yuval Noah Harari',
        genre: 'Non-Fiction',
        year: 2011,
        stock: 8,
      },
      {
        title: 'Educated',
        author: 'Tara Westover',
        genre: 'Memoir',
        year: 2018,
        stock: 10,
      },
      {
        title: 'Becoming',
        author: 'Michelle Obama',
        genre: 'Memoir',
        year: 2018,
        stock: 11,
      },
    ];

    await bookRepository.save(books);

    console.log('Seed data inserted');

    await connection.close();
  } catch (error) {
    console.error('Error seeding data:', error);
  }
}

seed();
